spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/editor-markdown
      username: root
      password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates
    request-context-attribute: re
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
img:
  location: E:/work/coding/java/IDEAWorkSpace/markdown/editor-markdown/upload/
logging:
  level: debug